# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpy2d()

# Create processing for single profile, then redo for all
import numpy as np
for i in range(1,46+1):
    for d in range(1,3):
        inname='Grid14-dir%d-Rawdata/FILE____%03d.DZT' %(d,i)
        mygpr.importdata(inname)
        mygpr.remMeanTrace(99999999)
        mygpr.setZeroTime(14)
        mygpr.truncateY(7)
        mygpr.setVelocity(0.06)
        mygpr.fkMigration()
        mygpr.topoCorrect('Grid-dir%d-Topo/TopoLine%02d.txt' %(d,i),
                          delimiter='\t')
        outname='Grid-dir%d-Processed/Line%02d.gpr' %(d,i)
        mygpr.save(outname)
